\begin{interimC}{luf-saxpy-C}{A truncatted version of the C++ stage function generated by the back-end compiler for the saxpy computation stage of the Block-LU factorization task.}
{// scope entrance for parallel loop on index i
int i;
int iterationStart = uPartDims[0].range.min;
int iterationBound = uPartDims[0].range.max;
int indexIncrement = 1;
int indexMultiplier = 1;
// ommitted code
int iXformed;
for (iXformed = iterationStart; 
		indexMultiplier * iXformed <= iterationBound; 
		iXformed += indexIncrement) {
	{ // scope start for index retransformation
	xformIndex = iXformed;
	partConfig = *(&lpu->uPartDims[0])->parent;
	xformIndex = ((xformIndex / partition.b) 
			* partConfig.count + partConfig.index) 
			* partition.b + xformIndex % partition.b;
	i = xformIndex;
	} // scope end for index retransformation
	long int iu_block0 = 
		((long) (iXformed - u_blockStoreDims[0].range.min)) 
		* ((long) (u_blockStoreDims[1].length));
	long int iu0 = ((long) (iXformed - uStoreDims[0].range.min)) 
		* ((long) (uStoreDims[1].length));
	{// scope entrance for parallel loop on index j
	int j;
	int iterationStart = uPartDims[1].range.min;
	int iterationBound = uPartDims[1].range.max;
	int indexIncrement = 1;
	int indexMultiplier = 1;
	// ommitted code
	for (j = iterationStart; 
			indexMultiplier * j <= iterationBound; j += indexIncrement) {
		long int jl_block1 = ((long) (j - l_blockStoreDims[1].range.min));
		long int ju1 = ((long) (j - uStoreDims[1].range.min));
		total = 0;
		{// scope entrance for parallel loop on index m
		int m;
		int iterationStart = u_blockPartDims[1].range.min;
		int iterationBound = u_blockPartDims[1].range.max;
		int indexIncrement = 1;
		int indexMultiplier = 1;
		// ommitted code
		for (m = iterationStart; indexMultiplier * m <= iterationBound; 
				m += indexIncrement) {
			long int mu_block1 = (m - u_blockStoreDims[1].range.min);
			long int ml_block0 = (m - l_blockStoreDims[0].range.min) 
				* (l_blockStoreDims[1].length);
			total = (total + (lpu->u_block[iu_block0 + mu_block1] 
				* lpu->l_block[ml_block0 + jl_block1]));
		}
		}// scope exit for parallel loop on index m
		lpu->u[iu0 + ju1] = (lpu->u[iu0 + ju1] - total);
	}
	}// scope exit for parallel loop on index j
}
}// scope exit for parallel loop on index i
return SUCCESS_RUN;
\end{interimC}
